### ISSUE TITLE
Azure Function ExchangeSyncFunction not running and Meeting room not found

### ISSUE THREAD

**Issue by aldvintumbelaka** [OfficeDev/microsoft-teams-apps-bookaroom#12]
Hi, I got an issue while trying to retrieve all available rooms.
It's not showing any option and got error message on the bottom.
![image](https://user-images.githubusercontent.com/33532350/81900043-71ffa580-95ff-11ea-9d91-344cef7b78f0.png)

When I check my function app (ExchangeSyncFunction) in the monitor tab, there is no run at all.
I try to wait for 1 day but seems like nothing running as well.
![image](https://user-images.githubusercontent.com/33532350/81900333-ea666680-95ff-11ea-8707-8827e1fb7841.png)

Try to trigger the ExchangeSyncFunction manually, it returns 202 accepted, but still nothing in the monitor tab.
![image](https://user-images.githubusercontent.com/33532350/81900378-036f1780-9600-11ea-9fb9-c603e23fb40e.png)

I've follow the deployment guide and I've made sure that all resources or services are available in the region that I select withing my resource group.

**Comment by abbodh** [comment]
Hi @aldvintumbelaka , can you please confirm below - 

1. Rooms and RoomLists are available in your tenant. 

> Book-a-room bot reads the list of rooms and room list from Exchange using Microsoft Graph APIs. The application expects all meeting rooms to be a part of room list. Room lists are specially marked distribution groups that you can use the same way you use distribution groups. Please follow the steps outlined if you do not have room list create a room list first and add existing rooms in the room list.

2. If you have the rooms and roomLists configured, then please check the azure storage table "RoomCollection" to see if it has the rooms listed down. The searchable dropdown refers to same table to get the list of rooms and the Az function "ExchangeSync" is responsible to add/update/delete the rooms every Sunday at 12 AM.

**Comment by rimvel** [comment]
How do i manually trigger update?

**Comment by aldvintumbelaka** [comment]
hi @abbodh it's working now after I add all rooms to the room list. Previously I only have 1 rooms those are included in the rooms list. Thanks
