### ISSUE TITLE
Deployment issue 

### ISSUE THREAD

**Issue by Mikhail2k15** [OfficeDev/microsoft-teams-apps-bookaroom#15]
![image](https://user-images.githubusercontent.com/11201670/86440249-cd523800-bd12-11ea-9489-8e85c372cb3f.png)

**Comment by abbodh** [comment]
Hi @Mikhail2k15 - this could be due to recent updates in Azure app services to work with .Net 3.1 and there is a need to explicitly force the kudu deployment to use 2.1 version.
