### ISSUE TITLE
Issue on the Az Function

### ISSUE THREAD

**Issue by sergiosanchezd** [OfficeDev/microsoft-teams-apps-bookaroom#3]
Hi,
I deployed this solution and I got the next error on the execution of the azure function:

"Error with data source: Table 'RoomCollection' does not exist.  Please adjust your data source definition in order to proceed"

Can someone help me? Maybe I had an error on the resources, but I think that it is correct.

Thanks,

**Comment by gagankohli2000** [comment]
I'm getting same error. Were you able to find solution?

**Comment by sergiosanchezd** [comment]
No sorry... I don't know whats appends....

**Comment by abbodh** [comment]
Hi @sergiosanchezd - can you please confirm if implict grant permission for Access token and ID token are provided during app registration i.e. Step 1 in Deployment Guide and Place.Read.All permission consent is provided under Graph API permissions.

**Comment by abbodh** [comment]
@sergiosanchezd is it working for you now?

**Comment by sergiosanchezd** [comment]
Hi, no... I had the same problem.

**Comment by abbodh** [comment]
Can you please confirm if the exchange has rooms and all rooms are tagged under roomList? 

Book-a-room bot reads the list of rooms and room list from Exchange using Microsoft Graph APIs. The application expects all meeting rooms to be a part of room list. Room lists are specially marked distribution groups that you can use the same way you use distribution groups. Please follow the steps outlined if you do not have room list [create a room list](https://docs.microsoft.com/en-us/exchange/recipients/room-mailboxes?view=exchserver-2019#create-a-room-list) first and add existing rooms in the room list.

**Comment by sergiosanchezd** [comment]
I don't have room list, so maybe is that the problem. I will try as soon as I can and I will inform you
