### ISSUE TITLE
Getting erorr in Function Error with data source: Table 'RoomCollection' does not exist.  Please adjust your data source definition in order to proceed.

### ISSUE THREAD

**Issue by gagankohli2000** [OfficeDev/microsoft-teams-apps-bookaroom#4]
Error with data source: Table 'RoomCollection' does not exist.  Please adjust your data source definition in order to proceed.

**Comment by sergiosanchezd** [comment]
Did you solve it?

**Comment by abbodh** [comment]
Hi @gagankohli2000 , can you please confirm if implict grant permission for Access token and ID token are provided during app registration i.e. Step 1 in [Deployment Guide](https://github.com/OfficeDev/microsoft-teams-apps-bookaroom/wiki/Deployment-guide) and Place.Read.All permission consent is provided under Graph API permissions.

**Comment by abbodh** [comment]
Closing the issue. Please create a new issue if the problem still persist.

**Comment by gagankohli2000** [comment]
@abbodh - In our case issue was with tenancy. I believe Place Graph APIs were not enabled on our tenant. Microsoft fixed this issued from backend.
